[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.97.3"
  HUGO_ENABLEGITINFO = "FALSE"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

# Redirect section
[[redirects]]
  from = "/category/physio"
  to = "/project/physio"
  status = 301
  force = true

[[redirects]]
  from = "/category/molecbio"
  to = "/project/molecbio"
  status = 301
  force = true

[[redirects]]
  from = "/category/ecoevo"
  to = "/project/ecoevo"
  status = 301
  force = true

[[redirects]]
  from = "/category/microbio"
  to = "/project/microbio"
  status = 301
  force = true

[[redirects]]
  from = "/category/environhealth"
  to = "/project/environhealth"
  status = 301
  force = true